CREATE DATABASE CLINICA_DB
collate Latin1_General_CI_AI
GO
USE CLINICA_DB
GO

CREATE TABLE TIPOUSUARIOS (
	IdTipoUsuario INT NOT NULL IDENTITY(1,1) ,
	Nombre VARCHAR(50) NOT NULL,
	PRIMARY KEY (IdTipoUsuario)
		);
GO

CREATE TABLE USUARIOS (
	IDUsuario INT NOT NULL  IDENTITY(1,1),
	Usuario VARCHAR(50) NOT NULL,
	Pass VARCHAR(50) NOT NULL,
	IdTipoUsuario INT NOT NULL,
	FechaAlta DATE NOT NULL DEFAULT(GETDATE()),
	FechaBaja DATE,
	PRIMARY KEY (IDUsuario),
	FOREIGN KEY (IdTipoUsuario) REFERENCES TIPOUSUARIOS (IdTipoUsuario)
);
GO


CREATE TABLE ESPECIALIDADES (
	IDEspecialidad INT NOT NULL IDENTITY(1,1) ,
	Nombre VARCHAR(255) NOT NULL,
	PRIMARY KEY (IDEspecialidad)
	);
GO

CREATE TABLE MEDICOS (
	IDMedico INT NOT NULL IDENTITY(1,1) ,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255) NOT NULL,
	IDEspecialidad INT,
	Matricula INT,
	FechaAlta DATE NOT NULL DEFAULT(GETDATE()),
	FechaBaja DATE,
	PRIMARY KEY (IDMedico),
	FOREIGN KEY (IDEspecialidad) REFERENCES ESPECIALIDADES (IDEspecialidad)
	);
GO


CREATE TABLE PACIENTES (
	IDPaciente INT NOT NULL IDENTITY(1,1) ,
	Nombre VARCHAR(255) NOT NULL,
	Apellido VARCHAR(255),
	DNI INT NOT NULL,
	Email VARCHAR(255),
	FechaNacimiento DATE,
	ObraSocial VARCHAR(255),
	FechaAlta DATE NOT NULL DEFAULT(GETDATE()),
	FechaBaja DATE,
	Habilitado BIT NOT NULL DEFAULT '1',
	PRIMARY KEY (IDPaciente)
);
GO


CREATE TABLE ESTADO_TURNOS (
	IDEstado INT NOT NULL IDENTITY(1,1) ,
	Nombre VARCHAR(50),
	PRIMARY KEY (IDEstado)
);
GO

CREATE TABLE TURNOS (
	IDTurno INT NOT NULL IDENTITY(1,1) ,
	IDMedico INT NOT NULL,
	IDPaciente INT NOT NULL,
	Fecha DATETIME,
	Observaciones TEXT,
	FechaAlta DATE NOT NULL DEFAULT(GETDATE()),
	IDEstado INT,
	PRIMARY KEY (IDTurno),
	FOREIGN KEY (IDMedico) REFERENCES MEDICOS (IDMedico),
	FOREIGN KEY (IDPaciente) REFERENCES PACIENTES (IDPaciente),
	FOREIGN KEY (IDEstado) REFERENCES ESTADO_TURNOS (IDEstado)
);
GO


