USE [master]
GO
/****** Object:  Database [CLINICA_DB]    Script Date: 22/6/2025 16:50:42 ******/
CREATE DATABASE [CLINICA_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CLINICA_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CLINICA_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CLINICA_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CLINICA_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CLINICA_DB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLINICA_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CLINICA_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CLINICA_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CLINICA_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CLINICA_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CLINICA_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CLINICA_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CLINICA_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CLINICA_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CLINICA_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CLINICA_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CLINICA_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CLINICA_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CLINICA_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CLINICA_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CLINICA_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CLINICA_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CLINICA_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CLINICA_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CLINICA_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CLINICA_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CLINICA_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CLINICA_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CLINICA_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CLINICA_DB] SET  MULTI_USER 
GO
ALTER DATABASE [CLINICA_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CLINICA_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CLINICA_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CLINICA_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CLINICA_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CLINICA_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CLINICA_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CLINICA_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CLINICA_DB]
GO
/****** Object:  Table [dbo].[ESPECIALIDADES]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESPECIALIDADES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](100) NULL,
	[Habilitado] [bit] NOT NULL,
 CONSTRAINT [PK_ESPECIALIDADES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEDICOS]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEDICOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Matricula] [int] NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Apellido] [varchar](100) NOT NULL,
	[Documento] [varchar](20) NOT NULL,
	[Email] [varchar](100) NULL,
	[Telefono] [varchar](50) NULL,
	[Nacionalidad] [varchar](50) NULL,
	[Provincia] [varchar](30) NULL,
	[Localidad] [varchar](30) NULL,
	[Calle] [varchar](150) NULL,
	[Altura] [int] NULL,
	[CodPostal] [varchar](10) NULL,
	[Depto] [varchar](50) NULL,
	[FechaNacimiento] [date] NULL,
	[EspecialidadesIDs] [varchar](max) NULL,
	[IDTurnoTrabajo] [int] NULL,
	[DiasDisponiblesIDs] [varchar](max) NULL,
	[HoraInicioBloque] [time](0) NULL,
	[HoraFinBloque] [time](0) NULL,
	[Habilitado] [bit] NULL,
 CONSTRAINT [PK_MEDICOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Matricula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Matricula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEDICOxESPECIALIDAD]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEDICOxESPECIALIDAD](
	[IDMedico] [int] NOT NULL,
	[IDEspecialidad] [int] NOT NULL,
 CONSTRAINT [PK_MEDICOxESPECIALIDAD] PRIMARY KEY CLUSTERED 
(
	[IDMedico] ASC,
	[IDEspecialidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OBRASOCIAL]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OBRASOCIAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](50) NULL,
	[Habilitado] [bit] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PACIENTES]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PACIENTES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Apellido] [varchar](100) NULL,
	[Documento] [int] NULL,
	[Email] [varchar](100) NULL,
	[Telefono] [varchar](50) NULL,
	[Nacionalidad] [varchar](50) NULL,
	[ProvinciaId] [varchar](30) NULL,
	[LocalidadId] [varchar](30) NULL,
	[Calle] [varchar](150) NULL,
	[Altura] [int] NULL,
	[CodPostal] [varchar](10) NULL,
	[Depto] [varchar](50) NULL,
	[FechaNacimiento] [date] NULL,
	[ObraSocialId] [int] NULL,
	[Observaciones] [varchar](max) NULL,
	[Habilitado] [bit] NULL,
 CONSTRAINT [PK_PACIENTES] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 22/6/2025 16:50:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [varchar](50) NULL,
	[Pass] [varchar](50) NULL,
	[TipoUser] [int] NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESPECIALIDADES] ADD  CONSTRAINT [DF_ESPECIALIDADES_Habilitado]  DEFAULT ((1)) FOR [Habilitado]
GO
ALTER TABLE [dbo].[MEDICOS] ADD  DEFAULT ((1)) FOR [Habilitado]
GO
ALTER TABLE [dbo].[OBRASOCIAL] ADD  CONSTRAINT [DF_OBRASOCIAL_Habilitado]  DEFAULT ((1)) FOR [Habilitado]
GO
ALTER TABLE [dbo].[PACIENTES] ADD  DEFAULT ((1)) FOR [Habilitado]
GO
ALTER TABLE [dbo].[MEDICOxESPECIALIDAD]  WITH CHECK ADD  CONSTRAINT [FK_MEDICOxESPECIALIDAD_ESPECIALIDADES] FOREIGN KEY([IDEspecialidad])
REFERENCES [dbo].[ESPECIALIDADES] ([ID])
GO
ALTER TABLE [dbo].[MEDICOxESPECIALIDAD] CHECK CONSTRAINT [FK_MEDICOxESPECIALIDAD_ESPECIALIDADES]
GO
ALTER TABLE [dbo].[MEDICOxESPECIALIDAD]  WITH CHECK ADD  CONSTRAINT [FK_MEDICOxESPECIALIDAD_MEDICOS] FOREIGN KEY([IDMedico])
REFERENCES [dbo].[MEDICOS] ([Id])
GO
ALTER TABLE [dbo].[MEDICOxESPECIALIDAD] CHECK CONSTRAINT [FK_MEDICOxESPECIALIDAD_MEDICOS]
GO
USE [master]
GO
ALTER DATABASE [CLINICA_DB] SET  READ_WRITE 
GO
