INSERT INTO TIPOUSUARIOS (Nombre) VALUES ('Administrador');
INSERT INTO TIPOUSUARIOS (Nombre) VALUES ('Recepcionista');
INSERT INTO TIPOUSUARIOS (Nombre) VALUES ('Médico');
INSERT INTO USUARIOS (Usuario, Pass, IdTipoUsuario) VALUES ('admin', 'admin', 1);
INSERT INTO USUARIOS (Usuario, Pass, IdTipoUsuario) VALUES ('recepcionista', 'recepcionista', 2);
INSERT INTO USUARIOS (Usuario, Pass, IdTipoUsuario) VALUES ('medico', 'medico', 3);
INSERT INTO ESPECIALIDADES (Nombre) VALUES ('Cardiología');
INSERT INTO ESPECIALIDADES (Nombre) VALUES ('Pediatría');
INSERT INTO ESPECIALIDADES (Nombre) VALUES ('Dermatología');
INSERT INTO ESPECIALIDADES (Nombre) VALUES ('Neurología');
INSERT INTO ESPECIALIDADES (Nombre) VALUES ('Ginecología');
INSERT INTO MEDICOS (Nombre, Apellido, IDEspecialidad, Matricula) VALUES ('Laura', 'Gómez', 1, 1001);
INSERT INTO MEDICOS (Nombre, Apellido, IDEspecialidad, Matricula) VALUES ('Carlos', 'Pérez', 2, 1002);
INSERT INTO MEDICOS (Nombre, Apellido, IDEspecialidad, Matricula) VALUES ('María', 'López', 3, 1003);
INSERT INTO MEDICOS (Nombre, Apellido, IDEspecialidad, Matricula) VALUES ('Javier', 'Fernández', 4, 1004);
INSERT INTO MEDICOS (Nombre, Apellido, IDEspecialidad, Matricula) VALUES ('Ana', 'Martínez', 5, 1005);
INSERT INTO PACIENTES (Nombre, Apellido, DNI, Email, FechaNacimiento, ObraSocial) VALUES ('Lucía', 'García', 30111222, 'lucia@mail.com', '1990-05-10', 'OSDE');
INSERT INTO PACIENTES (Nombre, Apellido, DNI, Email, FechaNacimiento, ObraSocial) VALUES ('Diego', 'Torres', 28123456, 'diegot@mail.com', '1985-08-20', 'Swiss Medical');
INSERT INTO PACIENTES (Nombre, Apellido, DNI, Email, FechaNacimiento, ObraSocial) VALUES ('Mariana', 'Suárez', 30999888, 'msuarez@mail.com', '2000-01-01', 'Galeno');
INSERT INTO PACIENTES (Nombre, Apellido, DNI, Email, FechaNacimiento, ObraSocial) VALUES ('Pablo', 'Rojas', 27876543, 'projas@mail.com', '1978-11-15', 'Medicus');
INSERT INTO PACIENTES (Nombre, Apellido, DNI, Email, FechaNacimiento, ObraSocial) VALUES ('Camila', 'Ramírez', 32456789, 'camila.r@mail.com', '1995-03-30', 'OSDE');
INSERT INTO ESTADO_TURNOS (Nombre) VALUES ('Pendiente');
INSERT INTO ESTADO_TURNOS (Nombre) VALUES ('Confirmado');
INSERT INTO ESTADO_TURNOS (Nombre) VALUES ('Cancelado');
INSERT INTO ESTADO_TURNOS (Nombre) VALUES ('Atendido');
INSERT INTO ESTADO_TURNOS (Nombre) VALUES ('No asistió');
INSERT INTO TURNOS (IDMedico, IDPaciente, Fecha, Observaciones, IDEstado) VALUES (1, 1, '2025-06-05 09:00', 'Chequeo general', 1);
INSERT INTO TURNOS (IDMedico, IDPaciente, Fecha, Observaciones, IDEstado) VALUES (2, 2, '2025-06-05 10:30', 'Control pediátrico', 2);
INSERT INTO TURNOS (IDMedico, IDPaciente, Fecha, Observaciones, IDEstado) VALUES (3, 3, '2025-06-06 11:00', 'Erupción cutánea', 1);
INSERT INTO TURNOS (IDMedico, IDPaciente, Fecha, Observaciones, IDEstado) VALUES (4, 4, '2025-06-06 12:15', 'Dolor de cabeza', 4);
INSERT INTO TURNOS (IDMedico, IDPaciente, Fecha, Observaciones, IDEstado) VALUES (5, 5, '2025-06-07 08:45', 'Estudios de rutina', 2);
